name: develop deploy

on:
  push:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y libcunit1-dev gcc

      - name: Build
        run: |
          chmod +x build.sh
          ./build.sh
          cd build

      - name: deploy
        run: |
          cd build
          ./cicd_pipeline